INSERT INTO artist (name) VALUES
       ('Kartezjusz'),
       ('Taco Hemingway'),
       ('Pezet'),
       ('Kendrick Lamar'),
       ('J. Cole'),
       ('Drake'),
       ('Beyoncé'),
       ('Ed Sheeran'),
       ('Adele'),
       ('Daft Punk'),
       ('Tame Impala'),
       ('Arctic Monkeys'),
       ('BTS'),
       ('Blackpink'),
       ('Taylor Swift'),
       ('Travis Scott'),
       ('Eminem'),
       ('Post Malone'),
       ('Rihanna'),
       ('The Weeknd');
